### ISSUE TITLE
Debian 10 安装过程提示 “mw” 错误

### ISSUE THREAD

**Issue by YI--** [midoks/mdserver-web#184]
## 什么系统 ?

Debian 10(4.19.0-21-amd64)；VirtualBox 虚拟中的

## 错误信息 ?

按罗列顺序执行

首次执行
```
curl -fsSL https://cdn.jsdelivr.net/gh/midoks/mdserver-web@latest/scripts/install.sh | bash
```
错误：
```
Starting mw-tasks... ./cli.sh: line 20: /www/server/mdserver-web/logs/task.log: No such file or directory
failed
------------------------------------------------------
tail: cannot open '/www/server/mdserver-web/logs/task.log' for reading: No such file or directory
------------------------------------------------------
Error: mw-tasks service startup failed.

.....................start mw fail
Time consumed: 13 Minute!
```

第二次执行
```
curl -fsSL https://cdn.jsdelivr.net/gh/midoks/mdserver-web@latest/scripts/install.sh | bash

```
结果
```
./cli.sh: line 38: gunicorn: command not found
Starting mw-tasks... failed
------------------------------------------------------
Traceback (most recent call last):
  File "task.py", line 11, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
------------------------------------------------------
Error: mw-tasks service startup failed.
.....................start mw fail
Time consumed: 5 Minute!
```
第三次执行
```
curl -fsSL https://cdn.jsdelivr.net/gh/midoks/mdserver-web@latest/scripts/update.sh | bash

```
结果
```
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/160.2 kB ? eta -:--:--
ERROR: Exception:
Traceback (most recent call last):
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
    yield
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 370, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    version=version,
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    version=version,
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 489, in _prepare_linked_requirement
    hashes,
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 169, in unpack_url
    hashes=hashes,
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/www/server/mdserver-web/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Requirement already satisfied: gevent-websocket==0.10.1 in ./lib/python3.7/site-packages (0.10.1)
Requirement already satisfied: gevent in ./lib/python3.7/site-packages (from gevent-websocket==0.10.1) (21.12.0)
Requirement already satisfied: zope.interface in ./lib/python3.7/site-packages (from gevent->gevent-websocket==0.10.1) (5.4.0)
Requirement already satisfied: zope.event in ./lib/python3.7/site-packages (from gevent->gevent-websocket==0.10.1) (4.5.0)
Requirement already satisfied: greenlet<2.0,>=1.1.0 in ./lib/python3.7/site-packages (from gevent->gevent-websocket==0.10.1) (1.1.3)
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from gevent->gevent-websocket==0.10.1) (65.3.0)
Requirement already satisfied: flask-caching==1.10.1 in ./lib/python3.7/site-packages (1.10.1)
Requirement already satisfied: Flask in ./lib/python3.7/site-packages (from flask-caching==1.10.1) (2.2.2)
Requirement already satisfied: click>=8.0 in ./lib/python3.7/site-packages (from Flask->flask-caching==1.10.1) (8.1.3)
Requirement already satisfied: itsdangerous>=2.0 in ./lib/python3.7/site-packages (from Flask->flask-caching==1.10.1) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in ./lib/python3.7/site-packages (from Flask->flask-caching==1.10.1) (3.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./lib/python3.7/site-packages (from Flask->flask-caching==1.10.1) (4.12.0)
Requirement already satisfied: Werkzeug>=2.2.2 in ./lib/python3.7/site-packages (from Flask->flask-caching==1.10.1) (2.2.2)
Requirement already satisfied: typing-extensions>=3.6.4 in ./lib/python3.7/site-packages (from importlib-metadata>=3.6.0->Flask->flask-caching==1.10.1) (4.3.0)
Requirement already satisfied: zipp>=0.5 in ./lib/python3.7/site-packages (from importlib-metadata>=3.6.0->Flask->flask-caching==1.10.1) (3.8.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.7/site-packages (from Jinja2>=3.0->Flask->flask-caching==1.10.1) (2.1.1)
stop mw
start mw
Starting mw-tasks... failed
------------------------------------------------------
Traceback (most recent call last):
  File "task.py", line 11, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "task.py", line 11, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
------------------------------------------------------
Error: mw-tasks service startup failed.
.......start mw success
==================================================================
MW-Panel default info!
==================================================================
MW-Panel-Url-Ipv4: http://xxx.xxx.xxx.xxx:7200 
MW-Panel-Url-Ipv6: http://[x:x:x:::]:7200
username: ouzkjegw
password: 2lndgsdn
Warning:
If you cannot access the panel, 
release the following port (7200|888|80|443|22) in the security group
==================================================================
```

## 错误截图 ?

第三次执行的结果

<img width="612" alt="image" src="https://user-images.githubusercontent.com/10511182/188600175-4b9a3a89-5541-41d9-9cd7-f057b596a666.png">

...

## 浏览器版本 ?
Chrome  104
...

## 软件版本(插件/面板) ?
0.97
...

目前结果面板可以登录，软件无法安装

**Comment by midoks** [comment]
软件无法安装?  举例，并给错误日志，猜测是有些库，没有安装成功，也有可能是原代码没有下载成功!

**Comment by midoks** [comment]
就是缺少psutil，后台任务需要它。安装后，service mw restart.

**Comment by YI--** [comment]
> 

👌，谢谢应该是这个问题
