### ISSUE TITLE
Ubuntu22 安装面板产生的问题 附日志

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [midoks/mdserver-web#196]
## 什么系统 ?

系统：Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1016-oracle x86_64)
面板：0.9.9 
安装链接：curl -fsSL https://cdn.jsdelivr.net/gh/midoks/mdserver-web@latest/scripts/install.sh | bash

## 错误信息 ?
安装面板的时候好像出现一个错误，但是面板正常安装，好像没什么问题。
```
  Downloading gevent-21.12.0.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 18.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 481, in <module>
          run_setup(EXT_MODULES)
        File "setup.py", line 348, in run_setup
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-la36x3l9/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-la36x3l9/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-la36x3l9/overlay/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
          ffi = FFI()
        File "/tmp/pip-build-env-la36x3l9/overlay/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.15.1, located in '/tmp/pip-build-env-la36x3l9/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

## 错误信息 ?
php74 80都无法安装
```
I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_ast.c -o Zend/zend_ast.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_objects.c -o Zend/zend_objects.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_object_handlers.c -o Zend/zend_object_handlers.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_objects_API.c -o Zend/zend_objects_API.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_default_classes.c -o Zend/zend_default_classes.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_inheritance.c -o Zend/zend_inheritance.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_smart_str.c -o Zend/zend_smart_str.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc 	-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_cpuinfo.c -o Zend/zend_cpuinfo.lo
/bin/sh /www/server/source/php/php74/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/www/server/source/php/php74/Zend/ -DPHP_ATOM_INC -I/www/server/source/php/php74/include -I/www/server/source/php/php74/main -I/www/server/source/php/php74 -I/www/server/source/php/php74/ext/date/lib -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/www/server/source/php/php74/ext/mbstring/libmbfl -I/www/server/source/php/php74/ext/mbstring/libmbfl/mbfl -I/www/server/source/php/php74/TSRM -I/www/server/source/php/php74/Zend    -g -O2 -fvisibility=hidden -Wall -Wno-strict-aliasing -DZEND_SIGNALS   -c /www/server/source/php/php74/Zend/zend_execute.c -o Zend/zend_execute.lo
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make: *** [Makefile:1645: Zend/zend_execute.lo] Error 1

```

## 错误信息 ?
版本：openresty-1.21.4.1 
OP防火墙不生效。

## 错误信息 ?
firewalld防火墙没有安装，具体没看当时的日志，也没有保存
后期自行https://github.com/midoks/mdserver-web/blob/master/scripts/install/ubuntu.sh看代码安装好的。

在此感谢作者，望答复。

**Comment by midoks** [comment]
1. cc: fatal error: Killed signal terminated program cc1  --> 这个错误是被系统kill了。多安装几次，， 获取升级cpu或内存。
2. gevent 没有升级成功，可能会影响 ssh终端。  --> 可以执行 update.sh 或手动操作 。 实在不行，就要换pip源。
3. OP防火墙 。 部分生效。 以前报错，现在不报错。 -> 下一个大版本，重点更新。
