### ISSUE TITLE
mysql添加数据库失败

### ISSUE THREAD

**Issue by q27598** [midoks/mdserver-web#218]
## 什么系统 ?

Debian GNU/Linux 11

## 错误信息 ?
数据库管理密码错误

点主从配置跳出：
Traceback (most recent call last): File "/www/server/mdserver-web/plugins/mysql/index.py", line 2471, in print(getMasterStatus(version)) File "/www/server/mdserver-web/plugins/mysql/index.py", line 1703, in getMasterStatus if len(dlist) > 0 and (dlist[0]["Slave_IO_Running"] == 'Yes' or dlist[0]["Slave_SQL_Running"] == 'Yes'): TypeError: object of type 'OperationalError' has no len()

#

**Comment by midoks** [comment]
执行一下更新脚本，看还出现不。

**Comment by q27598** [comment]
执行了 而且重启mysql还是出现

**Comment by hang666** [comment]
mariadb也有同样的问题

**Comment by midoks** [comment]
这是因为安装mysql和mariadb初始化失败。偶然会出问题。 现在添加了修复功能。

如果密码错误，会出现。 `数据库密码错误,在管理列表-点击【修复】!`，按照对应操作，即可正常运行。
