### ISSUE TITLE
PostgreSQL does not work well on Oracle Cloud Ampere A1 Compute Instance

### ISSUE THREAD

**Issue by sider2vf** [midoks/mdserver-web#266]
## 什么系统 ?

Debian 11

## 错误信息 ?

1. When I click on "Current Status" in the PostgreSQL administration, it throws the following error: 

```
Traceback (most recent call last): File "/www/server/mdserver-web/plugins/postgresql/index.py", line 1561, in print(runInfo()) File "/www/server/mdserver-web/plugins/postgresql/index.py", line 428, in runInfo time_local = time.localtime(int(timestamp)) ValueError: invalid literal for int() with base 10: ''
```

2. When I create a new database using the PostgreSQL admin list, it doesn't work and the slow log shows that it didn't do anything like create a user, database, or set a password.

## 错误截图 ?

![image](https://user-images.githubusercontent.com/116246824/203074699-cbaedfdd-59ad-4ad2-befa-e7d84bc816d0.png)

## 浏览器版本 ?

Microsoft Edge 107.0.1418.52

## 软件版本(插件/面板) ?

0.10.2

**Comment by midoks** [comment]
Version 0.11.0 has been optimized
