### ISSUE TITLE
甲骨文arm安装出错

### ISSUE THREAD

**Issue by malou8** [midoks/mdserver-web#364]
## 什么系统 ?

Debian 11

## 错误信息 ?

Traceback (most recent call last):
  File "/www/server/mdserver-web/tools.py", line 225, in <module>
    mwcli(clinum)
  File "/www/server/mdserver-web/tools.py", line 50, in mwcli
    print("(1)      \u91cd\u542f\u9762\u677f\u670d\u52a1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-14: ordinal not in range(256)

甲骨文DD纯净的Debian11系统后安装mw出错，几台机子都是这样

**Comment by midoks** [comment]
已经把编码信息加入了，mw update 即可
